### ISSUE TITLE
refacto

### ISSUE THREAD

**Issue by Identity-labs** [ptwu/distributed-texasholdem#19]
Why all logic in socket.on('moveMade' is not in game class ?

**Comment by ptwu** [comment]
Good point. I made this whole game at breakneck pace (and there are still some gameplay bugs to do with multiple all-in situations), and definitely made some awful engineering decisions (forgive me).

I'll refactor it eventually.

**Comment by Identity-labs** [comment]
I want to use your engine inside a gamemod, you can put on your readme what we need to fix, I want to help you improve this engine. Make some unit tests ect ...

**Comment by ptwu** [comment]
Most of the issues are tracked just through the Issues tab. The engine is actually fully functional but it seems that the game logic is flawed in `game.js`'s `distributeMoney` function (money is improperly partitioned when more than 2 people win due to naive sidepot calculation method that probably needs to be rewritten) and `moveOntoNextPlayer` (can result in an infinite loop when someone all-ins but has less money than the other players, so it thinks that the round is going on forever).  

I hope the code is maintainable enough... the code for handling moves is currently in `app.js`, client-side rendering in `main.js`, and most game logic in `game.js`. Unit tests would be a great addition, maybe we can integrate Jest?
